spring.application.name=tibcoLogger
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}

server.port=${PORT}

app.query.fixed=